name: PR CI
on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run formatter
        run: poetry run black --check .
      - name: Run linter
        run: poetry run flake8 .
      - name: Run tests
        run: poetry run pytest tests/
